### PR TITLE
added support for ESP32 devices

### LINKED ISSUE #5: ESP32 adapt
Dear,
Could you help me toadapt your lib for an ESP32 board?
Lot of error messages when building the code.
Thanks a lot

### PR DESCRIPTION
**Pull request by michaelkamprath**
Added support for ESP32 devices, and specifically tested in a Wemos LINOL32 LITE device.
Also fixed a bug with the Conway Game of Life examples. Closes #5

### CODE REVIEW

**Comment by gurvansz** [comment]
Thanks @michaelkamprath i will try today with my ESP32-WROOM-32 Espressif and come back to you

**Comment by sixtyfive** [comment]
Hi, trying to get it working with a board that's seemingly a copy of the [NodeMCU ESP32-S](https://docs.zerynth.com/latest/_images/nodemcu_esp32_pin.jpg). Pins D7,5,8 don't seem to be the correct ones and the code is a mystery to me (it seems only one pin is configurable at all?) What's the way for figuring out the correct pins?

**Comment by michaelkamprath** [comment]
@sixtyfive I don't readily know. You will need to find its ISP pins for MOSI and Clock, and then the latch pin can be something that you set (see documentation for how), though it defaults to 5 on ESP-32.

**Comment by sixtyfive** [comment]
thanks @michaelkamprath ... setting the latch pin was the one thing that was obvious from the code (it seems to be called slavePin there). anyways, with the help of somebody on freenode i've been able to make it work now and will open another PR adding that board's pin designations to the table.

**Comment by chnaeem** [comment]
@michaelkamprath 
I am stuck at integrating hub08 16x64 led panel with esp32 can you please send me the lib which you make for supporting esp32 and deleted 8 month ago

**Comment by michaelkamprath** [comment]
@chnaeem The changes I made to the `esp32` branch were merged into the `master` branch. The current library has the same code. If ou prefer to use the exact version you used 8 months ago, all you need to do is checkout that specific git commit instead. That specific git commit is at the top of this issue issue thread (that comes from the commit I made to address the issue you brought up). If you are unsure on how to checkout a specific git commit, google around, there are plenty of resources online on how to do that.

**Pull request merged**
